{
  "sksl": {
    "entrypoint": "background_shader_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform vec2 uMouse;\nuniform shader uTexture;\nuniform half2 uTexture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvec3 FLT_flutter_local_rect(vec2 st, vec2 size, vec2 position, float border, vec3 borderColor, vec3 backgroundColor)\n{\n    vec2 adjustedSt = st - position;\n    vec2 bl = floor(adjustedSt / size);\n    vec2 tr = floor((vec2(1.0) - adjustedSt) / size);\n    float inside = ((bl.x * bl.y) * tr.x) * tr.y;\n    float outline = step(0.0, inside - border);\n    return mix(backgroundColor, borderColor, vec3(outline));\n}\n\nvoid FLT_main()\n{\n    vec2 st_1 = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec3 color = vec3(0.0);\n    vec2 rectPosition = vec2(uSize.x - 0.100000001490116119384765625, 0.0);\n    vec2 param = st_1;\n    vec2 param_1 = vec2(0.20000000298023223876953125);\n    vec2 param_2 = rectPosition;\n    float param_3 = 0.100000001490116119384765625;\n    vec3 param_4 = vec3(0.0);\n    vec3 param_5 = vec3(0.800000011920928955078125, 0.699999988079071044921875, 0.5);\n    vec3 rectColor = FLT_flutter_local_rect(param, param_1, param_2, param_3, param_4, param_5);\n    color += rectColor;\n    fragColor = vec4(color, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 0,
        "name": "uTexture",
        "rows": 1,
        "type": 12
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uMouse",
        "rows": 2,
        "type": 10
      }
    ]
  }
}