{
  "sksl": {
    "entrypoint": "fog_shader_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\nuniform vec2 uCharacterPos;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_noise(vec2 st)\n{\n    return fract(sin(dot(st, vec2(12.98980045318603515625, 78.233001708984375))) * 43758.546875);\n}\n\nfloat FLT_flutter_local_fbm(inout vec2 st)\n{\n    float value = 0.0;\n    float amplitude = 0.5;\n    for (int i = 0; i < 5; i++)\n    {\n        vec2 param = st;\n        value += (amplitude * FLT_flutter_local_noise(param));\n        st *= 2.0;\n        amplitude *= 0.5;\n    }\n    return value;\n}\n\nvoid FLT_main()\n{\n    vec2 st_1 = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 characterNorm = uCharacterPos / uSize;\n    float distance = length(st_1 - characterNorm);\n    float smoothRadius = 2.0 / max(uSize.x, uSize.y);\n    float alpha = smoothstep(smoothRadius, smoothRadius + 0.100000001490116119384765625, distance);\n    fragColor = vec4(0.0, 0.0, 0.0, alpha);\n    vec2 param_1 = (st_1 * 3.0) + vec2(uTime * 8.9999997499035089276731014251709e-07);\n    float _124 = FLT_flutter_local_fbm(param_1);\n    float n = _124;\n    float cloudDensity = 2.0;\n    float cloudStrength = exp(distance * cloudDensity) * n;\n    vec4 cloudColor = vec4(0.800000011920928955078125, 0.800000011920928955078125, 0.800000011920928955078125, 1.0);\n    fragColor = cloudColor * cloudStrength;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uCharacterPos",
        "rows": 2,
        "type": 10
      }
    ]
  }
}