targets:
  $default:
    builders:
      freezed:
        options:
          fromJson: false
          toJson: false
          equal: true
          addImplicitFinal: true
          copyWith: true
          unionValueCase: pascal
          # enable for production only
          # format: false
