name: word_by_word_game
description: Word Arcade -> write word based on last 3 letters of last word & pass Landscape

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Commands:
# flutter pub outdated --mode=null-safety
# flutter run --no-sound-null-safety
# flutter pub run build_runner build
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.11+56

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  animate_do: ^3.0.2
  animated_text_kit: ^4.2.2
  bloc: ^8.1.2
  blur: ^3.1.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  firebase_analytics: ^10.4.3
  firebase_analytics_web: ^0.5.4+3
  firebase_core: ^2.15.0
  firebase_core_web: ^2.6.0
  firebase_crashlytics: ^3.3.4
  flame: ^1.17.0
  flame_bloc: ^1.11.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.4
  flutter_svg: ^2.0.7
  form_builder_validators: ^9.1.0
  freezed_annotation: ^2.2.0
  go_router: ^13.2.4
  google_fonts: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  life_hooks: ^0.0.19
  logger: ^2.0.2+1
  map_editor:
    path: packages/map_editor
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  path_to_regexp: ^0.4.0
  provider: ^6.0.5
  quiver: ^3.2.1
  recase: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  tiled: ^0.10.1
  universal_io: ^2.2.2
  url_launcher: ^6.1.11
  wbw_core:
    path: packages/wbw_core
  wbw_design_core:
    path: packages/wbw_design_core
  wbw_dictionaries:
    path: ./packages/wbw_dictionaries
  wbw_locale:
    path: packages/wbw_locale
dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  json_serializable: ^6.7.1
  melos: ^5.3.0
  msix: ^3.15.0
  xsoulspace_lints: ^0.0.10

dependency_overrides:
  collection: 1.18.0
  http: 1.0.0
  intl: ^0.19.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/promo/icon-512-green.png"
  ios: true
  android: true
  remove_alpha_ios: true

# For information see the following page:
# https://pub.dev/packages/flutter_gen
# flutter_gen:
#   # output: lib/gen/ # Optional (default: lib/gen/)
#   # line_length: 80 # Optional (default: 80)
#   # Optional
#   integrations:
#     flutter_svg: true
#     flare_flutter: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: false

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # fonts:
  #   - family: Raleway
  #     fonts:
  #       - asset: assets/fonts/Raleway-Regular.ttf
  #       - asset: assets/fonts/Raleway-Italic.ttf
  #         style: italic
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/ui_frames/
    - assets/images/buttons/
    # - assets/images/tilesets/
    # - assets/tiles/
    # - assets/icons/
    - google_fonts/
    # - assets/promo/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
