{
  "sksl": {
    "entrypoint": "snow_shader_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform float uTime;\nuniform vec2 uSize;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_superSnowyTime(float time, vec2 screenCoords)\n{\n    return cos(time) * 400.0;\n}\n\nfloat FLT_flutter_local_superSnowyEffectRandom(vec2 st)\n{\n    float param = uTime;\n    vec2 param_1 = st;\n    float time = FLT_flutter_local_superSnowyTime(param, param_1);\n    return fract((sin(dot(vec2(time) + st, vec2(time) + vec2(sin(time / 5000000.0), sin(time / 5000000.0)))) * 30000.0) / 0.300000011920928955078125);\n}\n\nvec4 FLT_flutter_local_superSnowyEffect(vec2 st)\n{\n    vec2 param = st;\n    float rnd = FLT_flutter_local_superSnowyEffectRandom(param);\n    float alpha = smoothstep(0.0, 0.4000000059604644775390625, rnd) * smoothstep(0.4000000059604644775390625, 0.0, rnd);\n    vec3 color = vec3(1.0, 0.800000011920928955078125, 0.5) * alpha;\n    return vec4(vec3(rnd) / vec3(1.0, 0.800000011920928955078125, 0.5), alpha);\n}\n\nvoid FLT_main()\n{\n    vec2 st_1 = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 param_1 = st_1;\n    vec4 color_1 = FLT_flutter_local_superSnowyEffect(param_1);\n    fragColor = color_1;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uSize",
        "rows": 2,
        "type": 10
      }
    ]
  }
}