name: map_playground
description: A new Flutter package project.
version: 0.0.1

# publish_to: "none"
# homepage:
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  bloc: ^8.1.0
  blur: ^3.1.0
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  equatable: ^2.0.5
  firebase_analytics: ^10.0.6
  firebase_analytics_web: ^0.5.1+5
  firebase_core: ^2.3.0
  firebase_core_web: ^2.0.1
  firebase_crashlytics: ^3.0.6
  flame: ^1.7.0
  flame_bloc: ^1.8.2
  flame_tiled: ^1.9.1
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_portal: ^1.1.3
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  life_hooks: ^0.0.18
  logger: ^1.1.0
  package_info_plus: ^2.0.0
  path: ^1.8.2
  path_provider: ^2.0.11
  path_to_regexp: ^0.4.0
  provider: ^6.0.4
  quiver: ^3.1.0
  recase: ^4.1.0
  rxdart: ^0.27.7
  sembast: ^3.3.1
  shared_preferences: ^2.0.15
  tiled: ^0.10.1
  universal_io: ^2.0.4
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.0
  flutter_gen_runner: 5.1.0+1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  xsoulspace_lints: ^0.0.8

# For information see the following page:
# https://pub.dev/packages/flutter_gen
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  # line_length: 80 # Optional (default: 80)
  # Optional
  assets:
    enabled: true
    outputs: null
    # gen_for_package: true
    # package_parameter_enabled: true

  integrations:
    #   flutter_svg: true
    flare_flutter: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/clouds/
    - assets/images/cursors/
    - assets/images/enemies/
    - assets/images/enemies/pearl/
    - assets/images/enemies/shell_left/
    - assets/images/enemies/shell_left/attack/
    - assets/images/enemies/shell_left/idle/
    - assets/images/enemies/shell_right/
    - assets/images/enemies/shell_right/attack/
    - assets/images/enemies/shell_right/idle/
    - assets/images/enemies/spikes/
    - assets/images/enemies/tooth/
    - assets/images/enemies/tooth/idle/
    - assets/images/enemies/tooth/run_left/
    - assets/images/enemies/tooth/run_right/
    - assets/images/items/
    - assets/images/items/diamond/
    - assets/images/items/gold/
    - assets/images/items/particle/
    - assets/images/items/silver/
    - assets/images/menu/
    - assets/images/player/
    - assets/images/player/fall_left/
    - assets/images/player/fall_right/
    - assets/images/player/idle_left/
    - assets/images/player/idle_right/
    - assets/images/player/jump_left/
    - assets/images/player/jump_right/
    - assets/images/player/run_left/
    - assets/images/player/run_right/
    - assets/images/preview/
    - assets/images/terrain/
    - assets/images/terrain/land/
    - assets/images/terrain/palm/large_bg/
    - assets/images/terrain/palm/large_fg/
    - assets/images/terrain/palm/left_bg/
    - assets/images/terrain/palm/left_fg/
    - assets/images/terrain/palm/right_bg/
    - assets/images/terrain/palm/right_fg/
    - assets/images/terrain/palm/small_bg/
    - assets/images/terrain/palm/small_fg/
    - assets/images/terrain/water/
    - assets/images/terrain/water/animation/
    - assets/json/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
