name: wbw_design_core
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_portal: ^1.1.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.1.0
  gap: ^2.0.0
  google_fonts: ^3.0.1
  life_hooks: ^0.0.18
  recase: ^4.1.0
  rive: ^0.10.2
  sliver_tools: ^0.2.5
  tap_builder: ^0.3.4

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  xsoulspace_lints: ^0.0.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # fonts:
  #   - family: la_icons
  #     fonts:
  #       - asset: packages/la_design_core/fonts/la_icons.ttf
