name: wbw_design_core
description: design ui kit
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  blur: ^3.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_hooks: ^0.18.6
  flutter_portal: ^1.1.4
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  google_fonts: ^5.1.0
  life_hooks: ^0.0.18
  recase: ^4.1.0
  rive: ^0.11.4
  sliver_tools: ^0.2.10
  tap_builder: ^0.4.1
  wbw_core:
    path: ../wbw_core

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  xsoulspace_lints: ^0.0.9

dependency_overrides:
  http: 1.0.0
  collection: 1.18.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # assets:
  #   - assets/images/
  # To add assets to your application, add an assets section, like this:
  assets:
    - google_fonts/
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # fonts:
  #   - family: la_icons
  #     fonts:
  #       - asset: packages/la_design_core/fonts/la_icons.ttf
