name: word-by-word-game
version: 2.7.1+29
summary: Word Arcade-> write word based on last 3 letters of last word & pass Landscape
description: |
  Please note: new version is completely rewritten and is in active development.
  Actual DevLog is available on https://arenukvern.itch.io/word-by-word-game and in Discord server https://discord.com/invite/y54DpJwmAn

  You can see also short video updates by the link below:
  https://youtube.com/playlist?list=PLz4tcEeusgWJeJO6RvOxOkfD3XE1pDKFg

  ----- Description -----

  Word by word - is a simple, fun, self-educative, and easy to play game to write word after word based on the last 3 letters of the last word.

  Features:

  - any word will be checked within internal dictionaries (available for two languages: English and Russian).
  - you can play with your friends in old school way - to give a turn to another player. (Players count now is unlimited).
  - works offline - no need internet connection.
  - UI translated to three languages (English, Russian, Italian).

  ## Have an idea, improvements, or bugs?

  Join Discord - https://discord.gg/y54DpJwmAn or send a message to idea@xsoulspace.dev.

  Have fun and a great time!
icon: snap/gui/word-by-word-game.png
confinement: strict
base: core18
grade: stable

slots:
  dbus-word-by-word-game:
    interface: dbus
    bus: session
    name: dev.xsoulspace.word_by_word_game # adjust accordingly

apps:
  word-by-word-game:
    command: word_by_word_game
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy

    slots:
      - dbus-word-by-word-game

parts:
  word-by-word-game:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
