name: word-by-word-game
version: 3.2.2+47
summary: Word Adventure-> write word based on 3 letters of last word & pass Landscape
description: |
  Please note: the game is in active development.
  Actual DevLog is available on https://arenukvern.itch.io/word-by-word-game and in Discord server https://discord.com/invite/y54DpJwmAn
  Or in Discord - https://discord.gg/y54DpJwmAn

  You can see also short video updates by the link below:
  https://youtube.com/playlist?list=PLz4tcEeusgWJeJO6RvOxOkfD3XE1pDKFg

  ----- Description -----

  Control the hot air balloon by entering unique words (within the level) based on the last 3 letters of the last word and bring it as far as you can!

  Features:

  - There is support for checking words in two languages (Russian and English). But if the word is not in the dictionary - you can add it.
  - You can play together with friends on the same device.
  - The game remembers the progress - if you press the menu (pause button in the center), the current game will be saved and you can continue later.
  - You can learn new words:)

  Have fun and a great time!
icon: snap/gui/word-by-word-game.png
confinement: strict
base: core18
grade: stable

slots:
  dbus-word-by-word-game:
    interface: dbus
    bus: session
    name: dev.xsoulspace.word_by_word_game # adjust accordingly

apps:
  word-by-word-game:
    command: word_by_word_game
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    # using dev as it is the one channel that supports linux
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy

    slots:
      - dbus-word-by-word-game
# https://forum.snapcraft.io/t/failed-to-install-or-refresh-a-snap-flutter-does-not-exist/25623
architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  word-by-word-game:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
